services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test 
      POSTGRES_PASSWORD: test 
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volume:/var/lib/psql
