services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: test
      POSTGRES_DATABASE: test 
      POSTGRES_USER: test 
      POSTGRES_PASSWORD: test 
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volume:/var/lib/psql
