[package]
name = "sqlx-conditional-queries-layering"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/o-dasher/sqlx-conditional-queries-layering.git"
description = "Query templating for sqlx-conditional-queries."
license = "MIT"

[workspace]
members = ["example"]
