CREATE TABLE owo (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE uwu (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE umu (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);
